export const TODO_ADD_LIST_ITEM = 'TODO_ADD_LIST_ITEM';
export const TODO_CHANGE_FILTER_STATUS = 'TODO_CHANGE_FILTER_STATUS';
export const TODO_CLEAR_COMPLETED_ITEMS = 'TODO_CLEAR_COMPLETED_ITEMS';
export const TODO_EDIT_LIST_ITEM_VALUE = 'TODO_EDIT_LIST_ITEM_VALUE';
export const TODO_EDIT_TOGGLE_LIST_ITEM = 'TODO_EDIT_TOGGLE_LIST_ITEM';
export const TODO_DELETE_LIST_ITEM = 'TODO_DELETE_LIST_ITEM';
export const TODO_TOGGLE_LIST_ITEM = 'TODO_TOGGLE_LIST_ITEM';
export const TODO_TOGGLE_ALL_LIST_ITEM = 'TODO_TOGGLE_ALL_LIST_ITEM';
