export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const TODO_ADD_LIST_ITEM = 'TODO_ADD_LIST_ITEM';
export const TODO_EDIT_LIST_ITEM_VALUE = 'TODO_EDIT_LIST_ITEM_VALUE';
export const TODO_EDIT_TOGGLE_LIST_ITEM = 'TODO_EDIT_TOGGLE_LIST_ITEM';
export const TODO_DELETE_LIST_ITEM = 'TODO_DELETE_LIST_ITEM';
export const TODO_TOGGLE_LIST_ITEM = 'TODO_TOGGLE_LIST_ITEM';
